In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Import Dataset 
data = pd.read_csv("surveyfile.csv")
data.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29,37,Female,United States,IL,NaN,No,Yes,Often,25-Jun,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29,32,Male,Canada,NaN,NaN,No,No,Rarely,25-Jun,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
Timestamp                    1259 non-null object
Age                          1259 non-null int64
Gender                       1259 non-null object
Country                      1259 non-null object
state                        744 non-null object
self_employed                1241 non-null object
family_history               1259 non-null object
treatment                    1259 non-null object
work_interfere               995 non-null object
no_employees                 1259 non-null object
remote_work                  1259 non-null object
tech_company                 1259 non-null object
benefits                     1259 non-null object
care_options                 1259 non-null object
wellness_program             1259 non-null object
seek_help                    1259 non-null object
anonymity                    1259 non-null object
leave                        1259 non-null object
mental_health_consequence    1259 non-null object
phys_health_consequence      1259 non-null object
coworkers                    1259 non-null object
supervisor                   1259 non-null object
mental_health_interview      1259 non-null object
phys_health_interview        1259 non-null object
mental_vs_physical           1259 non-null object
obs_consequence              1259 non-null object
comments                     164 non-null object
dtypes: int64(1), object(26)
memory usage: 265.6+ KB

In [4]:
#getting data with positive mental health consequences
mental_health_consequence_yes=data[data['mental_health_consequence'].str.contains("Yes")]
mental_health_consequence_yes.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
3,2014-08-27 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
12,2014-08-27 11:33,42,female,United States,CA,NaN,Yes,Yes,Sometimes,26-100,...,Somewhat difficult,Yes,Yes,Yes,Yes,Maybe,Maybe,No,Yes,NaN
25,2014-08-27 11:37,35,male,United States,TN,No,Yes,Yes,Sometimes,More than 1000,...,Very easy,Yes,No,Some of them,Yes,No,Yes,No,No,Sometimes I think about using drugs for my me...
29,2014-08-27 11:38,37,Male,United Kingdom,NaN,No,No,No,Sometimes,25-Jun,...,Very difficult,Yes,Maybe,Some of them,No,No,Maybe,No,No,NaN
30,2014-08-27 11:39,32,Male,United Kingdom,NaN,No,No,No,Never,25-Jun,...,Don't know,Yes,Yes,Some of them,Some of them,No,Maybe,No,No,NaN

In [5]:
#adding further columns affecting the mental health
mental_health_location=mental_health_consequence_yes[mental_health_consequence_yes['leave'].str.contains("Very easy")]
mental_health_location.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
25,2014-08-27 11:37,35,male,United States,TN,No,Yes,Yes,Sometimes,More than 1000,...,Very easy,Yes,No,Some of them,Yes,No,Yes,No,No,Sometimes I think about using drugs for my me...
36,2014-08-27 11:41,29,Male,Canada,NaN,No,No,No,Rarely,05-Jan,...,Very easy,Yes,Maybe,Some of them,No,No,No,Don't know,No,NaN
63,2014-08-27 11:50,26,Male,France,NaN,No,No,No,NaN,26-100,...,Very easy,Yes,No,No,No,No,No,No,Yes,NaN
209,2014-08-27 13:05,26,male,Bulgaria,NaN,No,No,No,NaN,100-500,...,Very easy,Yes,Maybe,No,No,No,Maybe,Don't know,No,NaN
219,2014-08-27 13:09,41,Male (CIS),United States,VA,No,No,No,NaN,26-100,...,Very easy,Yes,No,No,Some of them,No,No,Don't know,No,NaN

In [6]:
#getting the count
mental_health_location_hist = mental_health_location.groupby(['Country'])['mental_health_consequence'].count()

In [7]:
#printing the output
print(mental_health_location_hist)

Country
Bahamas, The      1
Bulgaria          1
Canada            2
Finland           1
France            1
Germany           1
Netherlands       1
United Kingdom    2
United States     8
Name: mental_health_consequence, dtype: int64

In [8]:
#filtering to a specific country
mental_health_location_uniquecountry = mental_health_location[mental_health_location['Country'].str.contains("Canada")].groupby(['Country'])['mental_health_consequence'].count()

In [9]:
#getting the output
print(mental_health_location_uniquecountry)

Country
Canada    2
Name: mental_health_consequence, dtype: int64